# Generated by Django 6.0.7 on 2026-07-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_country_code_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.employee'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(blank=True, default='All', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual Leave (GL)'), ('Earned', 'Earned Leave (EL)'), ('Festival', 'Festival Leave (FL)'), ('Medical', 'Medical Leave (SL)'), ('Paid', 'Paid Leave'), ('Unpaid', 'Unpaid Leave'), ('Maternity', 'Maternity Leave'), ('Paternity', 'Paternity Leave'), ('WFH', 'Work From Home'), ('HalfDay', 'Half Day Leave')], max_length=20),
        ),
    ]
